service: response-handler

configValidationMode: error

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-2
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: v1/{message}
          method: get
          cors: true
