service: response-handler

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-2

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: v1/{message}
          method: get
          cors: true
